### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by smatthewenglish** [s-matthew-english/Blockchain_Project#2]
Improving paper: 

--> Ellicit the help of Johns lab at the OU- get them to contribute a section to flesh out what he had put originally

-->  Interesting Resources:
- http://on.wsj.com/1RzWk3P

**Comment by hedugaro** [comment]
Are these dates correct?

Semantics 2016
Abstract Submission Deadline    April 14, 2016 11:59 pm, Hawaii time
Paper Submission Deadline   April 21, 2016  11:59 pm, Hawaii time

**Comment by smatthewenglish** [comment]
Yeah- but maybe we can focus only on the ISWC one in Japan, I think that's
April 30.

Did you see my Skype message? I can't make it tonigt to Cologne-
unfortunately.

Also- I had an idea for the paper.

On Mon, Apr 4, 2016 at 4:24 PM, hedugaro notifications@github.com wrote:

> Are these dates correct?
> 
> Semantics 2016
> Abstract Submission Deadline April 14, 2016 11:59 pm, Hawaii time
> Paper Submission Deadline April 21, 2016 11:59 pm, Hawaii time
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/s-matthew-english/Blockchain_Project/issues/2#issuecomment-205319223

Ok. No problem. I can't too.
Can you fix the google drive link on the github readme? 
I want to upload some ideas I have for the paper.

**Comment by hedugaro** [comment]
Ok. No problem. I can't too. Can you fix the google drive link on the github readme? I want to upload some ideas I have for the paper.

https://drive.google.com/drive/folders/0BxVAKBzwjD0BUVc2bW5wNFpqa2c

**Comment by smatthewenglish** [comment]
What's wrong with it? When I clicked that it brought me to the Google Drive

**Comment by hedugaro** [comment]
![Sin títulos.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Sin%20t%C3%ADtulos-d9c21ca628143d1ad3a428aab72ff2d74b34e5d9dc34ebe7f26bfd8429a9f5d2.png)

Anyway I just want to share this doc:
https://docs.google.com/document/d/16jFz0ew7B02Hpgul-PH8uPMfNXNyZNU1B_mQdXN5Wco/edit?usp=sharing

**Comment by smatthewenglish** [comment]
wow- cool that this email chain gets saved here!
